name: HTSINFER

on: [push, pull_request]

jobs:
  build-and-test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2

    - name: Install
      run: |
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        bash miniconda.sh -b -p $HOME/miniconda
        source "$HOME/miniconda/etc/profile.d/conda.sh"
        hash -r
        conda config --set always_yes yes --set changeps1 no
        conda update -q conda
        conda info -a
        conda env create --file environment.yml
        conda env update --file environment-dev.yml
        mypy a.py
    
    - name: Tests
      run: |
        # style tests
        # flake8
        pylint --rcfile pylint.cfg a.py
        mypy a.py
        # unit tests